[2024-04-08 22:23:07,140][flwr][INFO] - Starting Flower simulation, config: num_rounds=10, no round_timeout
[2024-04-08 22:23:09,153][flwr][INFO] - Flower VCE: Ray initialized with resources: {'memory': 3296555828.0, 'node:127.0.0.1': 1.0, 'object_store_memory': 1648277913.0, 'CPU': 8.0, 'node:__internal_head__': 1.0}
[2024-04-08 22:23:09,153][flwr][INFO] - Optimize your simulation with Flower VCE: https://flower.ai/docs/framework/how-to-run-simulations.html
[2024-04-08 22:23:09,153][flwr][INFO] - Flower VCE: Resources for each Virtual Client: {'num_cpus': 2, 'num_gpus': 0.0}
[2024-04-08 22:23:09,158][flwr][INFO] - Flower VCE: Creating VirtualClientEngineActorPool with 4 actors
[2024-04-08 22:23:09,158][flwr][INFO] - [INIT]
[2024-04-08 22:23:09,159][flwr][INFO] - Requesting initial parameters from one random client
[2024-04-08 22:23:10,190][flwr][INFO] - Received initial parameters from one random client
[2024-04-08 22:23:10,190][flwr][INFO] - Evaluating initial global parameters
[2024-04-08 22:23:10,358][flwr][ERROR] - index 0 is out of bounds for dimension 0 with size 0
[2024-04-08 22:23:10,361][flwr][ERROR] - Traceback (most recent call last):
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/flwr/simulation/app.py", line 308, in start_simulation
    hist = run_fl(
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/flwr/server/server.py", line 483, in run_fl
    hist, elapsed_time = server.fit(
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/flwr/server/server.py", line 95, in fit
    res = self.strategy.evaluate(0, parameters=self.parameters)
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/flwr/server/strategy/fedavg.py", line 167, in evaluate
    eval_res = self.evaluate_fn(server_round, parameters_ndarrays, {})
  File "/Users/harindersingh/Documents/Ph.D. Work/testing/Testing Flower Framework/flower-simulation-step-by-step-pytorch/server.py", line 35, in evaluate_fn
    model.load_state_dict(state_dict, strict=True)
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1657, in load_state_dict
    load(self, state_dict)
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1645, in load
    load(child, child_state_dict, child_prefix)
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1645, in load
    load(child, child_state_dict, child_prefix)
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1639, in load
    module._load_from_state_dict(
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 110, in _load_from_state_dict
    super(_NormBase, self)._load_from_state_dict(
  File "/Users/harindersingh/miniconda/envs/flower_tutorial/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _load_from_state_dict
    input_param = input_param[0]
IndexError: index 0 is out of bounds for dimension 0 with size 0

[2024-04-08 22:23:10,362][flwr][ERROR] - Your simulation crashed :(. This could be because of several reasons. The most common are: 
	 > Sometimes, issues in the simulation code itself can cause crashes. It's always a good idea to double-check your code for any potential bugs or inconsistencies that might be contributing to the problem. For example: 
		 - You might be using a class attribute in your clients that hasn't been defined.
		 - There could be an incorrect method call to a 3rd party library (e.g., PyTorch).
		 - The return types of methods in your clients/strategies might be incorrect.
	 > Your system couldn't fit a single VirtualClient: try lowering `client_resources`.
	 > All the actors in your pool crashed. This could be because: 
		 - You clients hit an out-of-memory (OOM) error and actors couldn't recover from it. Try launching your simulation with more generous `client_resources` setting (i.e. it seems {'num_cpus': 2, 'num_gpus': 0.0} is not enough for your run). Use fewer concurrent actors. 
		 - You were running a multi-node simulation and all worker nodes disconnected. The head node might still be alive but cannot accommodate any actor with resources: {'num_cpus': 2, 'num_gpus': 0.0}.
Take a look at the Flower simulation examples for guidance <https://flower.ai/docs/framework/how-to-run-simulations.html>.
